#############################################################
# Computers in geoscience course - Day 3
# Characters

# Normally we call a single character a character, such as this
"C"

# IN R character values area actually the strings
"CIP"

# Single-quotes are permited, by they evaluate to double quoted string anyway
'CIP'

# you can have a variety of characters in it
"o8zt89pe4wztioajsdoigzsbeiuaé9we tzoeahfgéosdhil  dfg auidg ahdguihsdofhgs"

"^$?()[]"

"ßäéŐ%%"

# where return/enter is ussed a newline escape character is entered \n
gibberish <- "asl;dfasdf
sdhf
kasdf
sadf
"

gibberish

# displaying/printing to the console0
message(gibberish)

# character vectors
# this is a single 'character' value
"table"

# create a character vector with "table" and "chair" in it!
furniture <- c("table", "chair")
furniture[2]


# adding names to the values
favorite2 <- c(7,3,7,9,8,3,9,6,3,7,4,2,1,8,4,5,NA)

people <- c(
  "Therese",
  "Antonia",
  "Maria",
  "Sebastian",
  "Jakob",
  "Luke",
  "Johnny",
  "Hannes",
  "Nyamka",
  "Amber",
  "Ashley",
  "Nicholas",
  "George",
  "Anna",
  "Aarya",
  "Angelo",
  "Adam"
)

# attributes
# names attribute
names(favorite2) # NULL is not NA

# missing values vs NULL
length(NA)
length(NULL)

# replacement of names
names(favorite2) <- people
favorite2

# what does this line of code do?
names(favorite2) <- 1:length(favorite2)

# Assigns number names - they become characters!
favorite2

# access the names
names(favorite2)

# replace the names: get back the original names
names(favorite2) <- people

##### Replacement
# this is a subsetting expression -> how do we replace things?
furniture
furniture[2]

# replace the second element with "desk"!
furniture[2] <- "desk"

# Gives awarning!
#furniture[1:2] <- c("a", "b", "c")

# replaces everytihng
furniture[1:2] <- c("sofa")
furniture

# Multiple comparisons Usually not used
favorite>c(1,5)

# the same as:
favorite>rep(c(1,5), 8)


# whose favorite number is 9?
favorite2==9
favorite2[which(favorite2==9)]

# please give me a vector of characters!
names(favorite2[which(favorite2==9)])
names(favorite2)[which(favorite2==9)]

# Jakob's favorite number
favorite2["Jakob"]

# same name for every value
# yo can always copy variables in R like this
favorite3 <- favorite2

# generally avoid having the same name in the names attributes
# R is trying to force the name to be unique.. Try to avoid these!
names(favorite3) <- "Everybody"
names(favorite3) <- rep("Everybody", length(favorite3))

# everybody - only the first value is returned
favorite3["Everybody"]


# character vectors can have names too!
anotherDummy <- people
names(anotherDummy) <- people
anotherDummy


################################################################################
# Data frames
df <- data.frame(
  people,
  favorite2
)

df

# spreadsheet rendering
View(df)

# column and rownames have to be there!
colnames(df)
rownames(df)

# manually name the columns
df2 <- data.frame(
  "name"=people,
  "favorite_number"=favorite2
)
colnames(df2)

# Rewrite column names with "person", "number"!
colnames(df2) <- c("person", "number")

# destroy the names - the automatic rownames are generated
# from the names attribute of favorite2
names(favorite3) <- NULL

# autogenerated rownames
df3 <- data.frame(
  "name"=people,
  "favorite_number"=favorite3
)

# Adding a logical vecotr
# Who are paleo master students?

# This gives an ERROR - has to have the same implied number of rows!
# paleomsc <- c(F,F,T,T,T,F,T,T,T,T,T,T,T,F,T,T)
# niceDF <- cbind(df2, paleomsc)

# this is good
paleomsc <- c(F,F,T,T,T,F,T,T,T,T,T,T,T,F,T,T,F)
niceDF <- cbind(df2, paleomsc)

################################################################################
# Some useful utility functions
# utility function
favorite2

# how many times do you see a value?
table(favorite2)

# the original values are in the names attribute
names(table(favorite2))

# another utility function - omit the duplicates!
unique(favorite2)

# unique() will include missing values
# unique() maintain the original order


################################################################################
# Accessing elemnts of a data.frame

# 1st: List-style subscript
niceDF$person

# access the paleomsc column
niceDF$paleomsc

# simple numeric subscript
niceDF$person[5]

# the names of people whose favorite number is 3
niceDF$person[which(niceDF$number==3)]
which(niceDF$number==3)

# 2nd: Matrix-style subscript
# niceDF[<ROWS>, <COLUMNS>]
niceDF[1, 1]
niceDF[2, 1]
niceDF[2, 3]
niceDF[2, 3]

# beyond bounds gives NULL
# favorite2[100]
# NULL
niceDF[200, 400]

# Examples
niceDF["Adam", "paleomsc"]
niceDF["Johnny", "person"]

# NULL
niceDF["ma", "bla"]

# entire rows and entire columns
# for column you will get a vector!
str(niceDF[ , "person"])

# for the rows 
# get the third row!
str(niceDF[ 3 , ]) # the structure 
niceDF[ 3 , ] # shown as a data.frame

# try to get a subset of the data!
# 10th to the 14th row
# first and the third column
niceDF[10:14 ,c(1, 3) ]

# get a subset for 
# Adam, Anna 
# whether we are paleo master students and our favorite numbers!

niceDF[c("Adam", "Anna"), c(2,3)]
niceDF[c("Adam", "Anna"), c("number","paleomsc")]

# The order matters!
niceDF[c("Anna", "Adam" ), c("paleomsc", "number")]
niceDF[c("Anna", "Adam", "Adam" ), c("paleomsc", "number")]

# The names of those people who are both 
# - paleo msc students
# - AND have a favorite number that is greater than 5!
#  (a logical AND operation is necessary!)

# Solution 1
niceDF$name[which(paleomsc==TRUE & favorite2>5)]

# Solution2 - Slightly more robust!
niceDF$name[niceDF$paleomsc==TRUE & niceDF$favorite_number>5]
# niceDF$name[which(niceDF$paleomsc==TRUE & niceDF$favorite_number>5)]


# if you remove or changes the paleomsc object, this will not longer work
rm(paleomsc)
#niceDF$name[which(paleomsc==TRUE & favorite2>5)] # ERROR!
